version: '3.8'

services:
  # web:
  #   build: ./project
  #   command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   volumes:
  #     - ./project:/usr/src/app
  #   ports:
  #     - 8004:8000
  #   environment:
  #     - ENVIRONMENT=dev
  #     - TESTING=0
  #     - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev        # new
  #     - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test  # new
  #   depends_on:   # new
  #     - web-db
  # new
  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web-adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
       - web-db

volumes:
  pgdata:
  
  